spring:
  application:
    name: equipcore-api
  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /api

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}